// <auto-generated />
namespace StoreClothing2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Porosia1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Porosia1));
        
        string IMigrationMetadata.Id
        {
            get { return "202109170819505_Porosia1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
